# Generated by Django 2.2.2 on 2019-07-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='category',
            field=models.CharField(choices=[('T', 'Tshirt'), ('S', 'Shirt'), ('B', 'Suits & Blazzers'), ('K', 'Kurtas'), ('BJ', 'Jeans'), ('BT', 'Trousers'), ('BS', 'Shorts'), ('BC', 'Cargos'), ('BP', 'Track pants')], max_length=2),
        ),
    ]
