# Generated by Django 2.2.2 on 2019-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20190704_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
