# Generated by Django 2.2.2 on 2019-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='sleeve',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
