# Generated by Django 2.2.2 on 2019-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20190723_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='fit',
            field=models.CharField(blank=True, default='Regular', max_length=50),
        ),
        migrations.AddField(
            model_name='men',
            name='size',
            field=models.CharField(blank=True, default='L', max_length=50),
        ),
    ]
