# Generated by Django 2.2.2 on 2019-08-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20190727_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='b2.jpg', upload_to='profile_pics'),
        ),
    ]
