# Generated by Django 2.2.2 on 2019-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_auto_20190808_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='contact',
            field=models.IntegerField(default='7878787878', max_length=10),
            preserve_default=False,
        ),
    ]
